name: Build ArpAttack for Windows 7

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scapy pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "ArpAttack_Win7" --uac-admin gui_arp.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArpAttack_Windows_Executable
        path: dist/ArpAttack_Win7.exe
